version: "3.4"

x-logging: &default-logging
   options:
      max-size: "10m"
      max-file: "4"
      tag: "{{.ImageName}}|{{.Name}}"
   driver: json-file

services:
  postgres:
    image: 'postgres:12.2'
    container_name: postgres_$PROJECT
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - postgres_credit:/var/lib/postgresql/data
    networks:
      - nodanorm_new


  front:
    container_name: $PROJECT
    build:
      context: .
    image: $AND_DOCKER_REGISTRY_NAME/$PROJECT:$CI_COMMIT_BRANCH
    ports:
      - 3001:8080
    restart: always
    logging: *default-logging
    networks:
      - nodanorm_new

volumes:
  postgres_credit:
    #- /var/lib/postgresql/data
    
networks:
  nodanorm_new:
    driver: bridge
