export enum CalculationMode {
  DIFFERENTIATED = 'DIFFERENTIATED',
  ANNUITY = 'ANNUITY',
}

export enum CardStatus {
  BLOCKED = 'BLOCKED',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  INDIVIDUAL_CONDITIONS = 'INDIVIDUAL_CONDITIONS',
}
