version: "3.4"


services:
  postgres:
    image: 'postgres:12.2'
    container_name: postgres_$PROJECT
    env_file: $AND_ENV
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres_credit:/var/lib/postgresql/data
    networks:
      - nodanorm_new


  credit-service:
    container_name: $PROJECT
    image: $AND_DOCKER_REGISTRY_NAME/$PROJECT:$CI_COMMIT_BRANCH
    ports:
      - $PORT:8080
    restart: always
    env_file: $AND_ENV
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        max-size: 300m
    networks:
      - nodanorm_new

volumes:
  postgres_credit:

    
networks:
  nodanorm_new:
    driver: bridge
